### PR TITLE
Move c-scape and c-gull into their own repo.

### PR DESCRIPTION
**Pull request by sunfishcode**
Similar to origin, move c-scape and c-gull into their own repo, which is now [here].

With this change, there's very little code left in the mustang repo here; it's just the custom target, some minimal glue code, and all the tests and examples.

This also renames the "threads" feature to "thread" following origin and now also c-gull and c-scape.

[here]: https://github.com/sunfishcode/c-ward

### CODE REVIEW

**Comment by notgull** [comment]
It might be useful to group all of the former mustang repos by an organization.

**Comment by sunfishcode** [comment]
Interesting idea. Perhaps the biggest question is, what should the name be? :wink: Which is perhaps to say, what should the unifying theme be? I myself am not clear on this yet.

**Comment by notgull** [comment]
> Perhaps the biggest question is, what should the name be?

Ideas:

- Maybe just `mustang-rs`, as that was the name of the original repo.
- `linux-raw-rs` and then also move `linux-raw-sys` to the org.
- All of the repos seem to be named after cars (Mustang, Origin, Seagull). So, maybe name it "Petal to the (Bare) Metal" or something.

**Comment by sunfishcode** [comment]
Thanks for the ideas! I'll ponder it.

Fwiw, I was aware of a car named Mustang, but not Origin or Seagull; those are coincidences.

This thread also reminds me of [this issue](https://github.com/sunfishcode/mustang/issues/1) in which I explained the choice of the name Mustang and learned that Mustang is also the name of a really nice place in Nepal.

**Pull request merged**
