### PR TITLE
Implement getcwd and chdir

### LINKED ISSUE #11: Implement `getcwd`, `chdir`
Rust's `std::env::current_dir` and `set_current_dir` are implemented by calls to `getcwd` and `chdir`. The first half in implementing these is to add support to `rsix`: these should go in `rsix::process`. There's already a `imp/linux_raw` implementation of the `getcwd` and `chdir` system calls, so this needs a `imp/libc` implementation which should just call the `libc` function, and then a public API in `src/process`. For `getcwd`, the public API should take care of allocating the buffer and growing it as needed until `getcwd` successfully writes the whole string, returning an `OsString`, similar to `readlinkat`.

The second step is to implement `c-scape` support in terms of the `rsix` public API. It may look odd to do it this way, because `rsix` will be dynamically allocating, and we'll need to copy the (sub)string out of the dynamic allocated buffer into the fixed-size requested buffer. But one of the goals for `c-scape` is to help test `rsix`, and to help prepare for `rsix` itself to be the low-level API instead of `c-scape`.

### PR DESCRIPTION
**Pull request by cole-miller**
Closes #11.

### CODE REVIEW

**Comment by sunfishcode** [comment]
Looks great! Could you check that calling `std::env::current_dir` and `std::env:;set_current_dir` from Rust, compiled to mustang, works? And if so, could you remove `current_dir` from the limitations section in the README.md?

**Comment by Urgau** [comment]
@sunfishcode Is it planned to add the file-descriptor (`fchdir`) variant of `chdir`?

**Comment by sunfishcode** [comment]
It doesn't look like Rust's `std` uses `fchdir`, and offhand I don't know of any popular Rust crates that use `fchdir`, so the use cases we have right now don't need it. But if someone wants to add it, that'd be fine too.

**Comment by cole-miller** [comment]
This should be ready (assuming I wrote the test correctly).

**Comment by sunfishcode** [comment]
Looks good!

**Pull request merged**
