### PR TITLE
c-scape: add pthread_setname_np (#139)

### PR DESCRIPTION
**Pull request by HookedBehemoth**
As mentioned in the issue #139, any code using threads fails to link. Since this commit, rust links against a pthread_setname_np on linux. Android is unaffected. https://github.com/rust-lang/rust/commit/013986be1bcfbfd9cedddf22dfd9584ccdb7ee6e

### CODE REVIEW

**Comment by sunfishcode** [comment]
The test failure is just that tests/examples.rs contains a nightly version string that needs to match the CI version.

**Comment by sunfishcode** [comment]
Otherwise, this PR looks good to me!

**Comment by HookedBehemoth** [comment]
Ah my bad.
I have some unrelated IP test fail there now
```
---- ip_properties stdout ----
thread 'ip_properties' panicked at 'assertion failed: !ip!(\"ff01::\").is_global()', tests/net-ip.rs:396:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- ipv6_properties stdout ----
thread 'ipv6_properties' panicked at 'assertion failed: !ip!(\"ff01::\").is_global()', tests/net-ip.rs:758:5```

**Comment by sunfishcode** [comment]
That's due to a change on Rust nightly. I happen to have a patch to update the test here: https://github.com/sunfishcode/mustang/commit/6011601abdfb3071e02f42656656b57d0ac3e3fa. In theory, cherry-picking that in should fix it.

**Comment by HookedBehemoth** [comment]
yep that passes all tests on my end 👍🏻

**Comment by sunfishcode** [comment]
Thanks!

**Pull request merged**
